const permissionCatalog = [
  'roles.read',
  'roles.create',
  'roles.update',
  'roles.delete',
  'permissions.assign',
  'permissions.revoke',
  'activity_logs.read',
  'activity_logs.export',
  'restaurants.read',
  'restaurants.create',
  'restaurants.update',
  'restaurants.suspend',
  'restaurants.delete',
  'branches.manage',
  'menus.read',
  'menus.manage',
  'menus.availability.update',
  'orders.read',
  'orders.create',
  'orders.accept',
  'orders.reject',
  'orders.status.update',
  'orders.cancel',
  'orders.refund.approve',
  'dispatch.read',
  'dispatch.assign',
  'riders.read',
  'riders.manage',
  'riders.status.update',
  'zones.read',
  'zones.manage',
  'fees.manage',
  'surge.manage',
  'customers.read',
  'customers.manage',
  'customers.blacklist',
  'promotions.read',
  'promotions.manage',
  'loyalty.manage',
  'analytics.read',
  'reports.export',
  'profile.manage',
  'users.manage',
];

const coreRoles = ['admin', 'owner', 'kitchen', 'rider', 'customer'];

module.exports = {
  permissionCatalog,
  coreRoles,
};
